# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dht22', '0002_auto_20160405_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
